language: objective-c
osx_image: xcode10.2
xcode_workspace: Movies App.xcworkspace
xcode_scheme: Movies App
xcode_destination: platform=iOS Simulator,OS=11.1,name=iPhone 8
before_install:
- pod repo update
